version: "3.9"

services:
  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn install && yarn styles:watch & yarn start --host 0.0.0.0"

  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - app
